package Common;

public enum Command {
    LOGIN , SIGNUP , LOGOUT , USERNAME_UNIQUE ,
    ADD_COMMENT , LIKE , DISLIKE , REPOST , UPDATE_PROFILE ,
    GET_POSTS , FOLLOW , UNFOLLOW , PUBLISH_POST ,
    GET_INFO , VIEW_COMMENTS , GET_PASSWORD
}
